source "https://rubygems.org"

gem "activerecord", "~> 5.0"
gem "pg"
gem "pry"
gem "rake"
gem "rack-test"
gem "sinatra", "~> 2.0"
gem "sinatra-activerecord", "~> 2.0"
gem "sinatra-contrib"

group :test do
  # gem "factory_girl"
  gem "rspec"
end
